version: "2"
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./Config:/config
      - ./Downloads:/downloads
    ports:
      - 81:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
